





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.0.1.0")]
  public partial class FMRS_Version_Info
  {
   public const string beta_version = "0";
   public const string version_number = "0.0.1.0";
  }