





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("1.2.0.6")]
  public partial class FMRS_Version_Info
  {
   public const string beta_version = "6";
   public const string version_number = "1.2.0.6";
  }